name: coverage
on:
  push:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: stable
    - run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test"
    - name: Calculate coverage
      run: |
        go test -v -covermode=atomic -coverprofile=cover.out.raw -coverpkg=./... ./...
        # remove generated code from coverage calculation
        grep -Ev 'internal/mock|_enumer.go' cover.out.raw > cover.out
    - name: Generage coverage badge
      uses: vladopajic/go-test-coverage@a93b868a4cbcbf18dc3781650fad241f0020e609 # v2.18.8
      with:
        profile: cover.out
        local-prefix: github.com/${{ github.repository }}
        git-token: ${{ secrets.GITHUB_TOKEN }}
        # orphan branch for storing badges
        git-branch: badges
