name: coverage
on:
  push:
    branches:
    - main
permissions: {}
jobs:
  coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: stable
    - run: |
        git config --global user.email "test@example.com"
        git config --global user.name "Test"
    - name: Calculate coverage
      run: |
        go test -v -covermode=atomic -coverprofile=cover.out.raw -coverpkg=./... ./...
        # remove generated code from coverage calculation
        grep -Ev 'internal/mock|_enumer.go' cover.out.raw > cover.out
    - name: Generage coverage badge
      uses: vladopajic/go-test-coverage@f94bcf0d6b9fa5fb8b783830b22648f6c17475e2 # v2.19.0
      with:
        profile: cover.out
        local-prefix: github.com/${{ github.repository }}
        git-token: ${{ secrets.GITHUB_TOKEN }}
        # orphan branch for storing badges
        git-branch: badges
