name: Tag and Release

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Configure Git
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Install ccv
      run: go get github.com/smlx/ccv
    - name: Bump tag if necessary
      id: tag
      run: |
        if [ -z $(git tag -l $(ccv)) ]; then
          git tag $(ccv)
          git push --tags
          echo "new=true" >> $GITHUB_OUTPUT
        fi
    - name: Run GoReleaser
      if: steps.tag.outputs.new == 'true'
      uses: goreleaser/goreleaser-action@v4.3.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
